@backend_HostAddress = http://localhost:5192

### Get all registrations
GET {{backend_HostAddress}}/api/registrations
Accept: application/json

###

### Add a new registration
POST {{backend_HostAddress}}/api/registrations
Content-Type: application/json
Accept: application/json

{
    "name": "John Doe",
    "cityStateCommittee": "Boston, MA / NECYPAA Committee",
    "phoneNumber": "123-456-7890",
    "email": "johndoe@example.com",
    "sobrietyDate": "May 15, 2020",
    "accessibilityNeeds": "Wheelchair access",
    "isPanelSpeaker": true,
    "isVolunteer": false,
    "paymentMethod": "PayPal",
    "transactionId": "PAY1234567890"
}