name: Deploy Backend Application

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Application
        run: |
          cd backend
          dotnet publish -c Release -o ./publish

      - name: Archive Application Files
        run: |
          cd backend/publish
          zip -r backend.zip ./*
          mv backend.zip ../../
          cd ../../

      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'backend.zip'
          target: '~/'
          timeout: 120

      - name: Deploy Application on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/app && mkdir ~/app
            unzip -o ~/backend.zip -d ~/app
            rm ~/backend.zip
            pkill -f "dotnet" || true
            nohup dotnet ~/app/backend.dll > ~/app/log.txt 2>&1 &
